app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'MainController@index');
Route::get('/services{name?}{description?}{min?}{max?}', ['as' => 'services', 'uses' => 'MainController@index']);

Route::auth();

Route::group(['prefix' => 'api'], function(){

    Route::post('authenticate', 'AuthenticateController@authenticate');
    Route::get('user/logged', 'AuthenticateController@getAuthenticatedUser');
    Route::post('register', ['as' => 'register', 'uses' => 'AuthenticateController@register']);//revisar

    Route::get('/services{name?}{description?}{min?}{max?}', ['as' => 'api.services', 'uses' => 'MainController@index']);
    Route::resource('categories', 'CategoryController', ['only' => 'index']);
    Route::get('/dashboard', 'DashboardController@index');
    Route::group(['prefix' => 'dashboard', 'middleware' => 'jwt.auth', 'jwt.refresh'], function(){
        Route::get('profiles', ['as' => 'dashboard.profiles.index', 'uses' => 'UserProfileController@index']);
        Route::get('profiles/create', ['as' => 'dashboard.profiles.create', 'uses' => 'UserProfileController@create']);
        Route::get('profiles/edit',['as' => 'dashboard.profiles.edit', 'uses' => 'UserProfileController@edit']);
        Route::post('profiles', ['as' => 'dashboard.profiles.store', 'uses' => 'UserProfileController@store']);
        Route::put('profiles',['as' => 'dashboard.profiles.update', 'uses' => 'UserProfileController@update']);
        Route::resource('users.services', 'UserServiceController');
    });
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $table = 'services';

    protected $fillable = [
        'category_id',
        'user_id',
        'name',
        'description',
        'price',
        'phone'
    ];

    public function category () {
        return $this->belongsTo('\App\Category');
    }

    public function user () {
       return $this->belongsTo('\App\User');
    }


    public function tags (){
        return $this->belongsToMany('App\Tag','service_tags', 'service_id', 'tag_id');
    }

}

resources/views/services/create.blade.php
@extends('......layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="{{ route('dashboard.users.services.store', ['users' => $service->user_id]) }}" method="POST">
             {{ csrf_field() }}
                @include('...services.partials.fields')
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12 no-padder">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-block" href="{{ url('dashboard/users/'. Auth::user()->id . '/services') }}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button>
                            </div>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-block">Save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/services/edit.blade.php
@extends('......layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="{{ asset('/dashboard/users/' . $service->user_id . '/services/' . $service->id)}}  " method="POST">
               {{ method_field('PUT') }}
                {{ csrf_field() }}
                @include('...services.partials.fields')
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12 no-padder">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-block" href="{{ url('dashboard/users/'. Auth::user()->id . '/services') }}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button>
                            </div>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-block">Save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/services/index.blade.php
@extends('......layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            @include('...services.partials.navbar')
            @include('...services.partials.table')
        </div>
    </div>
</div>
@endsection

resources/views/services/show.blade.php
@extends('......layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    @include('...services.partials.delete_confirm')
                    <div class="panel-heading">Services</div>
                        <div class="panel-body">
                            <div class="service-item col-md-12">
                                <div class="service-attribute col-md-3">ID</div><div class="col-md-9">{{ $service->id }}</div>
                            </div>
                            <div class="service-item col-md-12">
                                <div class="service-attribute col-md-3">Name</div><div class="col-md-9">{{ $service->name }}</div>
                            </div>
                            <div class="service-item col-md-12">
                                <div class="service-attribute col-md-3">Description</div><div class="col-md-9">{{ $service->description }}</div>
                            </div>
                            <div class="service-item col-md-12">
                                <div class="service-attribute col-md-3">Price</div><div class="col-md-9">{{ $service->price }}</div>
                            </div>
                        </div>
                    <div class="panel-footer">
                        <div class="text-right">
                            <form id="form-actions" action="{{ route('dashboard.users.services.destroy',['users' => $service->user_id, 'services' => $service->id])}}" method="POST">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <td class="text-center">
                                    <a href="{{ url('dashboard/users/' .$service->user_id . '/services') }}" class="btn btn-info btn-xs">
                                        <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                    </a>
                                    <button class="btn btn-xs btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-title="Delete User" data-message="Are you sure you want to delete this user ?">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </button>
                                    <a href="{{ url('dashboard/users/' .$service->user_id . '/services/' . $service->id.'/edit') }}" class="btn btn-primary btn-xs">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                    </a>
                                </td>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection